app_name: "Sample App"
base_title: "Ruby on Rails Tutorial Sample App"
default_locale: "en"
available_locales:
  - "en"
  - "vi"
  - "ja"
url:
  tutorial: "https://railstutorial.org"
  author: "https://www.michaelhartl.com"
  news: "https://news.railstutorial.org"
  rubyonrails: "https://rubyonrails.org"
  guides: "https://guides.rubyonrails.org"
  gravatar_template: "https://secure.gravatar.com/avatar/%{gravatar_id}?s=%{size}"
path:
  rails_logo: "rails.png"
regex:
  email: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  gravatar:
    medium_size: 80
    small_size: 50
    tiny_size: 30
  password_reset_expire_time: 2 # hours
micropost:
  content:
    max_length: 140
  image:
    content_type: ["image/jpeg", "image/gif", "image/png"]
    max_size: 5 # megabytes
    resize_to_limit: [500, 500] # width, height
users_per_page: 10
microposts_per_page: 10
mailer:
  default_from: "noreply@example.com"
